### ISSUE TITLE
can't run with arguments

### ISSUE THREAD

**Issue by thomas-oo** [Goodsmileduck/redis-cli#1]
Command: docker run --name=redis-cli -it --rm goodsmileduck/redis-cli -h localhost -p 5050 ping

Response: Error response from daemon: Cannot start container 66d5ba6734f7da6b807c0f2004aa8b543cbf91dcd521b405d8465b5a56543d05: [8] System error: exec: "-h": executable file not found in $PATH

**Comment by Leonardo18** [comment]
Same problem here

**Comment by Goodsmileduck** [comment]
@Leonardo18 you have to add commad in front parameters 
ex:
```
docker run --name=redis-cli -it --rm goodsmileduck/redis-cli redis-cli -h localhost -p 5050 ping
```

**Comment by Leonardo18** [comment]
Yeah @Goodsmileduck, yesterday i did this and works fine. Thanks, great job.

**Comment by DaveStein** [comment]
The docs also show `--it` instead of `-it`
