### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by icemouton** [Goodsmileduck/redis-cli#5]
documentation example should read as :
`docker run --rm --name redis-cli -it goodsmileduck/redis-cli redis-cli -h hostname -p 6379 ping`

The current instruction does not work.
Additionally there is another example in which has an extra - before the -it command
`docker run --name redis-cli -it goodsmileduck/redis-cli`

**Comment by Goodsmileduck** [comment]
sure. check this out @icemouton  https://github.com/Goodsmileduck/redis-cli/commit/54cf9060681247f4468c74e5f6e7bba70d74932b

**Comment by icemouton** [comment]
you're still missing the redis-cli command on line 31

should be
`docker run --rm --name redis-cli -it goodsmileduck/redis-cli redis-cli -h hostname -p 6379 ping`

I'm only reporting it because it took me a while to figure out
